### ISSUE TITLE
GUI-Home

### ISSUE THREAD

**Issue by SamKry** [Cryptric/TexCards#41]
TODO:
- [x] Button style
- [x] Links
- [x] Colors
- [x] Spacing
- [x] Footer 
- [x] Text Alignment
- [x] Features at small window

# 1. Button style

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/5fe1ed85-97dc-469a-8ec2-81c89977681a)

Most components use rounded corners (logo, Icons), but he buttons don't.

## Proposal (for discussion)

Edit/create button style to match look of other components. 

# 2. Links

A proposal in GUI enhancement:

## Current state

Does not have a link:
- Source Code **Lern More ->**
- Markdown **Lern More ->**
- **Features**

Needs a better Link:
- Mermaid **Lern More ->**

## Proposal (for discussion)

- Source Code: link to GitHub repo (this)?
  - cheat sheet?
- Markdown: 
  - [Markdown Cheat Sheet](https://www.markdownguide.org/cheat-sheet/)
  - [Markdown Cheatsheet by Adam Pritchard](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
- Mermaid: 
  - [Mermaid Cheat Sheet](https://jojozhuang.github.io/tutorial/mermaid-cheat-sheet/)
  - [About Mermaid](https://mermaid.js.org/intro/)

# 3. Colors

See issue #40 for color consistency.

Implement the color palette.

# 4. Spacing

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/dd82217d-4aab-4025-a048-fd88926b8e67)

Spacing (b) between Buttons and Features could be larger. 

## Proposal (for discussion)

Open for discussion. Perhaps resolved by point `6. Text Alignment` separating **Features** from Main View by different Background Color.

# 5. Footer

A proposal in GUI enhancement:

## Current state

See screenshot above: **(e)**.

The footer is too large in desktop view. if you make the window smaller (like tablet), the size of the footer shrinks. 

## Proposal (for discussion)

Use the footer size from tablet/phone for desktop as well.

# 6. Text Alignment

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/60d11b02-66b3-43a2-8614-88428d763880)

Mixing of Centred and Left-Aligned Text. 

## Proposal (for discussion)

Stick to centred like in this example:
![](https://www.searchenginejournal.com/wp-content/uploads/2019/10/screenshot_10-5dbac6bbbf7ad.jpg)

Or separate the **Features** from the main site like this:
![image](https://github.com/Cryptric/TexCards/assets/87971518/10a5d32b-204f-4354-941c-2a366c823d6f)

# 7. Features at small window

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/0eefe0d0-1bfa-4b3b-9599-0c6a64613aed)

The 4 features are too small. 

## Proposal (for discussion)

Enlarge the min-Width and wrap them on a new line on small windows.

**Comment by Cryptric** [comment]
for source code https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

**Comment by SamKry** [comment]
- center features
- add links to cheat sheets
- remove features button

**Comment by To-Ye** [comment]
Centered the text, by adding the class "text-center" to the columns in home.component.html: 

![image](https://github.com/Cryptric/TexCards/assets/104443170/a5f26dbf-6250-453d-b5f5-562300bfb1b8)

![image](https://github.com/Cryptric/TexCards/assets/104443170/9700e73c-313a-424f-9491-8bfe14bd691c)
