### ISSUE TITLE
GUI-Login/Register

### ISSUE THREAD

**Issue by SamKry** [Cryptric/TexCards#43]
TODO:

- [x] Button Style
- [x] Crazy with changes
- [x] Text sometimes multi-line
- [x] Button Text
- [ ] #61

# 1. Button Style

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/70a93d57-c048-45cc-9f9f-f033b44c51c5)

Inconsistent Button Styles.

## Proposal (for discussion)

Use the same buttons as in issue #41 proposed. (rounded corners). 
**Make sure it matches the style of the Text Fields (Username, Password)**

# 2. Crazy with changes

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/bab401d4-77a8-49bf-b828-25361f193362)
![image](https://github.com/Cryptric/TexCards/assets/87971518/e07afb50-3ae0-4538-b20b-c1bbf5db2c78)
![image](https://github.com/Cryptric/TexCards/assets/87971518/5bdc587d-c76b-4ddc-b124-0aa530b98b2a)

The Signup/Login Main View changes width un-proportional to the window's width. It even jumps back and forth between the different widths. 

## Proposal (for discussion)

Make sure the with stays the same or is proportional to the window's width. In my opinion the second looks great. 

# 3. Text sometimes multi-line

A proposal in GUI enhancement:

## Current state

See screenshots above. The text on the Login/Signup view sometimes wraps on two lines, sometimes on one.

## Proposal (for discussion)

On larger window: one line text. Wrap only then needed.

# 4. Button Text

A proposal in GUI enhancement:

## Current state

"sign up now" and "log in" must be capitalised -> "**S**ign up now" and "**L**og in" 

# 5. User Icon

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/bc4188a6-4d37-49a0-aa21-bc48e6f3718e)

The icon is round.

## Proposal (for discussion)

Perhaps use a square background with rounded corners (like other icons, just larger)

**Comment by Cryptric** [comment]
Fixed Crazy width changes by removing breaking points and setting max-width to 400px

**Comment by SamKry** [comment]
user icon moved to seperate issue
