### ISSUE TITLE
GUI-Dashboard

### ISSUE THREAD

**Issue by SamKry** [Cryptric/TexCards#45]
TODO:
- [x] Add create button (+)
- [x] Search bar

# 1. Add create button (+)

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/917632a4-fdcd-48fe-b900-93fd8238cda8)

When you do not have any cards, it's a bit counter intuitive to go to profile first to create a set. 

## Proposal (for discussion)

![image](https://github.com/Cryptric/TexCards/assets/87971518/4e6a21ac-6f0e-497a-9907-082fb4e8f272)

- Add a button next to `My Flashcards` to create a new set.
- Add a set named "Create your first Flashcard" which includes a tutorial (examples) of flashcards.

# 2. Search bar

A proposal in GUI enhancement:

## Current state

The search bar is quite large (seems to be important)

## Proposal (for discussion)

![image](https://github.com/Cryptric/TexCards/assets/87971518/c8f10a89-3065-43e7-96b9-fc8bdd0ff5e6)

Reduce the height to something similar to the icons on the top right.

**Comment by Cryptric** [comment]
Should a create button be added everywhere (i.e. on the profile page)?

**Comment by Cryptric** [comment]
How about hiding the recently studied section when there are none, and adding a banner with a button in the middle and a short text, like "No flashcard sets yet? Create one"

**Comment by SamKry** [comment]
> How about hiding the recently studied section when there are none, and adding a banner with a button in the middle and a short text, like "No flashcard sets yet? Create one"

Sounds good if it can be done!

**Comment by SamKry** [comment]
> Should a create button be added everywhere (i.e. on the profile page)?

You mean like the proposal in #46 :


![](https://user-images.githubusercontent.com/87971518/255853351-f6d7dc3a-c7f7-4e71-b027-c94392cd0551.png)

**Comment by Cryptric** [comment]
> Should a create button be added everywhere (i.e. on the profile page)?

no, just on dashboard, with icon and no text

**Comment by SamKry** [comment]
SF-Symbol
folder.fill.badge.plus

![folder fill badge plus@2x](https://github.com/Cryptric/TexCards/assets/87971518/e3675add-59d2-4fde-af1a-a4509034d6e5)

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE svg
PUBLIC "-//W3C//DTD SVG 1.1//EN"
       "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26.2598" height="18.623">
 <g>
  <rect height="18.623" opacity="0" width="26.2598" x="0" y="0"/>
  <path d="M3.06641 18.1836L19.4043 18.1836C21.1523 18.1836 22.1777 17.168 22.1777 15.1562L22.1777 11.2207C21.9238 11.25 21.6797 11.2598 21.4355 11.2598C18.7402 11.2598 16.4062 9.6582 15.4688 7.14844L0 7.14844L0 15.1562C0 17.1777 1.02539 18.1836 3.06641 18.1836ZM0 5.86914L15.1562 5.86914C15.1172 5.61523 15.0781 5.35156 15.0781 5.06836C15.0781 4.08203 15.3125 3.01758 15.7715 2.09961L9.73633 2.09961C9.07227 2.09961 8.67188 1.94336 8.18359 1.52344L7.58789 1.03516C6.94336 0.488281 6.44531 0.3125 5.47852 0.3125L2.69531 0.3125C0.986328 0.3125 0 1.28906 0 3.25195ZM21.2988 9.92188C23.9844 9.92188 26.2598 7.67578 26.2598 4.96094C26.2598 2.24609 24.0137 0 21.2988 0C18.5742 0 16.3379 2.24609 16.3379 4.96094C16.3379 7.69531 18.5742 9.92188 21.2988 9.92188ZM21.2988 8.07617C20.9277 8.07617 20.6934 7.83203 20.6934 7.4707L20.6934 5.56641L18.7891 5.56641C18.4277 5.56641 18.1934 5.33203 18.1934 4.96094C18.1934 4.59961 18.4277 4.36523 18.7891 4.36523L20.6934 4.36523L20.6934 2.46094C20.6934 2.09961 20.9277 1.86523 21.2988 1.86523C21.6602 1.86523 21.8945 2.09961 21.8945 2.46094L21.8945 4.36523L23.7988 4.36523C24.1602 4.36523 24.4043 4.59961 24.4043 4.96094C24.4043 5.33203 24.1602 5.56641 23.7988 5.56641L21.8945 5.56641L21.8945 7.4707C21.8945 7.83203 21.6602 8.07617 21.2988 8.07617Z" fill="#000000" fill-opacity="0.85"/>
 </g>
</svg>

**Comment by SamKry** [comment]
folder.badge.plus
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE svg
PUBLIC "-//W3C//DTD SVG 1.1//EN"
       "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26.2598" height="18.623">
 <g>
  <rect height="18.623" opacity="0" width="26.2598" x="0" y="0"/>
  <path d="M3.06641 18.1836L19.4043 18.1836C21.1523 18.1836 22.1777 17.168 22.1777 15.1562L22.1777 11.2109C21.7871 11.2793 21.1133 11.2891 20.6055 11.2109L20.6055 15.0879C20.6055 16.0938 20.0488 16.6113 19.082 16.6113L3.08594 16.6113C2.10938 16.6113 1.57227 16.0938 1.57227 15.0781L1.57227 3.33984C1.57227 2.37305 2.08008 1.875 3.01758 1.875L5.07812 1.875C5.72266 1.875 6.11328 2.04102 6.61133 2.46094L7.20703 2.95898C7.8418 3.48633 8.35938 3.67188 9.32617 3.67188L15.1172 3.67188C15.2344 3.11523 15.3711 2.64648 15.6445 2.09961L9.73633 2.09961C9.07227 2.09961 8.67188 1.94336 8.18359 1.52344L7.58789 1.03516C6.94336 0.488281 6.44531 0.3125 5.47852 0.3125L2.69531 0.3125C0.986328 0.3125 0 1.28906 0 3.25195L0 15.1562C0 17.1777 1.02539 18.1836 3.06641 18.1836ZM0.957031 7.24609L15.3906 7.24609C15.2148 6.77734 15.0879 6.2793 15.0391 5.77148L0.957031 5.77148ZM21.2988 9.92188C23.9844 9.92188 26.2598 7.67578 26.2598 4.96094C26.2598 2.24609 24.0137 0 21.2988 0C18.5742 0 16.3379 2.24609 16.3379 4.96094C16.3379 7.69531 18.5742 9.92188 21.2988 9.92188ZM21.2988 8.07617C20.9277 8.07617 20.6934 7.83203 20.6934 7.4707L20.6934 5.56641L18.7891 5.56641C18.4277 5.56641 18.1934 5.33203 18.1934 4.96094C18.1934 4.59961 18.4277 4.36523 18.7891 4.36523L20.6934 4.36523L20.6934 2.46094C20.6934 2.09961 20.9277 1.86523 21.2988 1.86523C21.6602 1.86523 21.8945 2.09961 21.8945 2.46094L21.8945 4.36523L23.7988 4.36523C24.1602 4.36523 24.4043 4.59961 24.4043 4.96094C24.4043 5.33203 24.1602 5.56641 23.7988 5.56641L21.8945 5.56641L21.8945 7.4707C21.8945 7.83203 21.6602 8.07617 21.2988 8.07617Z" fill="#000000" fill-opacity="0.85"/>
 </g>
</svg>

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE svg
PUBLIC "-//W3C//DTD SVG 1.1//EN"
       "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26.2598" height="18.623">
 <g>
  <rect height="18.623" opacity="0" width="26.2598" x="0" y="0"/>
  <path d="M3.06641 18.1836L19.4043 18.1836C21.1523 18.1836 22.1777 17.168 22.1777 15.1562L22.1777 11.2109C21.7871 11.2793 21.1133 11.2891 20.6055 11.2109L20.6055 15.0879C20.6055 16.0938 20.0488 16.6113 19.082 16.6113L3.08594 16.6113C2.10938 16.6113 1.57227 16.0938 1.57227 15.0781L1.57227 3.33984C1.57227 2.37305 2.08008 1.875 3.01758 1.875L5.07812 1.875C5.72266 1.875 6.11328 2.04102 6.61133 2.46094L7.20703 2.95898C7.8418 3.48633 8.35938 3.67188 9.32617 3.67188L15.1172 3.67188C15.2344 3.11523 15.3711 2.64648 15.6445 2.09961L9.73633 2.09961C9.07227 2.09961 8.67188 1.94336 8.18359 1.52344L7.58789 1.03516C6.94336 0.488281 6.44531 0.3125 5.47852 0.3125L2.69531 0.3125C0.986328 0.3125 0 1.28906 0 3.25195L0 15.1562C0 17.1777 1.02539 18.1836 3.06641 18.1836ZM0.957031 7.24609L15.3906 7.24609C15.2148 6.77734 15.0879 6.2793 15.0391 5.77148L0.957031 5.77148ZM21.2988 9.92188C23.9844 9.92188 26.2598 7.67578 26.2598 4.96094C26.2598 2.24609 24.0137 0 21.2988 0C18.5742 0 16.3379 2.24609 16.3379 4.96094C16.3379 7.69531 18.5742 9.92188 21.2988 9.92188ZM21.2988 8.07617C20.9277 8.07617 20.6934 7.83203 20.6934 7.4707L20.6934 5.56641L18.7891 5.56641C18.4277 5.56641 18.1934 5.33203 18.1934 4.96094C18.1934 4.59961 18.4277 4.36523 18.7891 4.36523L20.6934 4.36523L20.6934 2.46094C20.6934 2.09961 20.9277 1.86523 21.2988 1.86523C21.6602 1.86523 21.8945 2.09961 21.8945 2.46094L21.8945 4.36523L23.7988 4.36523C24.1602 4.36523 24.4043 4.59961 24.4043 4.96094C24.4043 5.33203 24.1602 5.56641 23.7988 5.56641L21.8945 5.56641L21.8945 7.4707C21.8945 7.83203 21.6602 8.07617 21.2988 8.07617Z" fill="#000000" fill-opacity="0.85"/>
 </g>
</svg>
