### ISSUE TITLE
GUI-Profile

### ISSUE THREAD

**Issue by SamKry** [Cryptric/TexCards#46]
TODO:
- [ ] #61 
- [x] TextField Style
- [x] Spacing
- [x] Button Style
- [ ] #62
- [x] Error messages
- [x] Min/Max values

# 1. Profile Picture

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/f65214da-cdb0-43e5-8958-bb77dc40d551)

There is only Username and email shown in profile.

## Proposal (for discussion)

Add profile picture in square with rounded corners to the left. 

![image](https://github.com/Cryptric/TexCards/assets/87971518/963094c3-108b-4c9c-8ee0-9bea41546e68)

When clicking on Picture, a popup is presented to replace/set the picture. (like on instagram for example):
![image](https://github.com/Cryptric/TexCards/assets/87971518/b930e694-0495-4a21-8455-6d35922abc5c)

# 2. TextField Style

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/1d4c10ba-25b6-4dc3-ab70-d3f4edea48ba)

The textfield style is mixed. 

## Proposal (for discussion)

Use the upper fields, but enlarge the corner radius to match the style of the icons. (The same for Buttons)

# 3. Spacing

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/79f06ec9-38e8-4132-8fb3-98536477d0a1)

The email address and "Learn scheduling settings:" is too close to each other. So are the `Save` and `Create New Flashcard Set` buttons.

## Proposal (for discussion)

- Add more spacing
- Move the buttons to the right. (The same for dashboard)

![image](https://github.com/Cryptric/TexCards/assets/87971518/f6d7dc3a-c7f7-4e71-b027-c94392cd0551)

# 4. Button Style

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/3f298f87-1b9f-4e9b-bf99-cd9134c8dd47)

The Buttons have a smaller corner radius than the icons.

## Proposal (for discussion)

- Enlarge the corner radius of the Button (and TextFields)
- Reduce the corner radius of the icons

# 5.  Change Username/Email/Password

A proposal in GUI enhancement:

## Current state

Currently the email, username and password can't be changed by the user anymore.

## Proposal (for discussion)

Add possibility to change email, username and password.

Add new part on the bottom of the profile site with the needed buttons to edit/update these.

# 6.  Error messages

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/a834f414-d044-4cca-a7e2-c781141d49db)

When passing a large number (like 2900000000) an empty error is shown. The same for `Easy` , larger than 25.

## Proposal (for discussion)

Fix problem by ether calculate time in second or add dropdown to select Unit (Seconds, Minutes, Hours, Days).

# 7.  Min/Max values

A proposal in GUI enhancement:

## Current state

Currently you can enter Negative numbers and large numbers throw error.

## Proposal (for discussion)

Expected Min Values: 

![image](https://github.com/Cryptric/TexCards/assets/87971518/cc326bf2-7477-4341-9633-65152fa2b649)

**Comment by To-Ye** [comment]
Increased the border-radius to 10px. Through this, we have a clear distinction between the input fields and buttons. I would leave the icons like they are, except the one that contains our "logo" (upper left corner), I would make that one round. 
![image](https://github.com/Cryptric/TexCards/assets/104443170/d76897cf-5862-4eb6-b6e7-74958a869e4b)

**Comment by Cryptric** [comment]
I would suggest using the same button style everywhere, also for the login/register page, with just slightly rounded corners, i.e. 5px, something like here on GitHub

**Comment by To-Ye** [comment]
To make all the buttons the same I had to remove the border radiuses in 
*profile.compononent.html* (can't remember the exact numbers):
- **line 59** 
- **line 53**

*login.component.html* (was 25px):
- **line 34**
- **line 43**

*register.component.html* (was 25px):
- **line 31**

Also I changed the radius to 5px, yielding the following results:

***Login-Page (night)***

![image](https://github.com/Cryptric/TexCards/assets/104443170/c5e148e2-7fc1-4c8f-8c77-d4cf9b9c54d9)

***Register-Page (night)***

![image](https://github.com/Cryptric/TexCards/assets/104443170/851d7c02-5a86-4b56-8884-abc35936bb5e)

***Account-settings-Page (night)***

![image](https://github.com/Cryptric/TexCards/assets/104443170/f164fde8-c687-4318-88a2-730f25e4b4ff)

***Login-Page (day)***

![image](https://github.com/Cryptric/TexCards/assets/104443170/ee861f4e-8dd7-4aa6-bf16-8000c956bbcf)

***Register-Page (day)***

![image](https://github.com/Cryptric/TexCards/assets/104443170/2a88619f-2159-4153-b1e0-c3287ea2dad9)

***Account-settings-Page (day)***

![image](https://github.com/Cryptric/TexCards/assets/104443170/9c655d8c-95a7-49ec-aae3-72de5a77a6dc)

**Comment by SamKry** [comment]
![image](https://github.com/Cryptric/TexCards/assets/87971518/705e2f51-f44a-46a0-9060-562c710a23e7)
If i understand/see correctly, the corner _radiuses_ are now different. (Larger on TextFields and smaller on Buttons)
Is this intended?

As discussed in #49 we will use the capsule design for tags and rounded corners for text fields and buttons. But i think we should then use the same radius for TxtFields and Btns.
What are your thoughts @To-Ye  and @Cryptric ?

**Comment by SamKry** [comment]
Option for private profile

**Comment by AlexTheTallCoder** [comment]
Change the backend to refrain from providing email addresses due to our privacy policy. Instead, provide an option to initiate the verification process for a new email address.

**Comment by Cryptric** [comment]
> ![image](https://user-images.githubusercontent.com/87971518/267394154-705e2f51-f44a-46a0-9060-562c710a23e7.png) If i understand/see correctly, the corner _radiuses_ are now different. (Larger on TextFields and smaller on Buttons) Is this intended?
> 
> As discussed in #49 we will use the capsule design for tags and rounded corners for text fields and buttons. But i think we should then use the same radius for TxtFields and Btns. What are your thoughts @To-Ye and @Cryptric ?

take everywhere the first one

**Comment by AlexTheTallCoder** [comment]
exclude @ from allowed characters for username to prevent email as username

**Comment by To-Ye** [comment]
Fixed the button radius on all of the buttons to 10px (same as input-form), please pull and see if you are content with it.

**Comment by To-Ye** [comment]
Excluded @ from allowed characters for username to prevent email as username
