### ISSUE TITLE
GUI-Search

### ISSUE THREAD

**Issue by SamKry** [Cryptric/TexCards#47]
TODO:
- [x] Search bar/Tag selector
- [x] Text
- [x] Show all Sets on begin
- [x] Duplicated Sets
- [x] Click on Tag
- [x] Button for add to collection
- [x] Save search query
- [x] Sort function
- [x] Hover Effect

# 1. Search bar/Tag selector

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/1abaecb4-01f8-411f-851e-4e7576e9764a)

The `Tags` selector is way too wide. 

## Proposal (for discussion)

Place it on the right side of the search bar if possible and only wrap it to new line on small devices.

![image](https://github.com/Cryptric/TexCards/assets/87971518/9192cc55-d7e3-4944-a5fe-bb606b912ece)

# 2. Text

A proposal in GUI enhancement:

## Current state

**Search Flashcard Sets**

In search bar: **Search term**
## Proposal (for discussion)

- add "for"? -> "Search **For** Flashcard Sets"
- change search term to **search...** like in the other views.

# 3. Show all Sets on begin

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/76de599e-3e85-4a49-9345-37528cf61e43)

When entering the search page, "no Result" is shown and no flash set.

## Proposal (for discussion)

Show all available Sets on begin and use the "Search" more as a filter.

# 4. Duplicated Sets

A proposal in GUI enhancement:

## Current state

Sometimes when searching for sets, every set is shown twice. 

# 5. Tags after Search

A proposal in GUI enhancement:

## Current state

![image](https://github.com/Cryptric/TexCards/assets/87971518/cba57d71-75bf-41eb-84e5-dc96dd38227f)

All tags are present in popup after searching.

## Proposal (for discussion)

Only show **available** tags after the search term was applied.

# 6. Click on Tag or Username

A proposal in GUI enhancement:

## Current state

Click on card opens set.

## Proposal (for discussion)

![image](https://github.com/Cryptric/TexCards/assets/87971518/92a34c1b-0b4f-4ae0-aa88-4d34648b8562)

Click on **Tag** should search/filter for this tag. Click on **Username** should lead to the User's public page (with all public sets, etc. )
- Add hover effect
- Add click

# 7. Button for add to collection

A proposal in GUI enhancement:

## Current state

No possibility to add a set quickly to collection.

## Proposal (for discussion)

![image](https://github.com/Cryptric/TexCards/assets/87971518/4a2a3ded-fd03-4f40-a4b9-4850cf876f05)

Add a button to add the set to the collection, ore remove it if already added.

# 8. Save search query

A proposal in GUI enhancement:

## Current state

When searching for cards, tags etc. then click on a card set and then go back, the search query is reset. Also the scroll position is up at top.

## Proposal (for discussion)

Save the search query (in URL?) like digitec for example does. This also allows to share the search with other users.

# 9a. Search for User Profiles

A proposal in GUI enhancement:

## Current state

No possibility to search for User names

## Proposal (for discussion)

Add possibility to search for User names. 
- With `@`in search field
- or in different field (like Tags)

# 9b. Sort function

A proposal in GUI enhancement:

## Current state

No possibility to sort searched sets

## Proposal (for discussion)

Add possibility to sort the sets. Possible sort attributes are:
- Last modified
- Date created
- Number of Cards
- Name
- Username

# 10. Hover Effect

A proposal in GUI enhancement:

## Current state

Quite static page, no hover effect to indicate a the click possibility.

## Proposal (for discussion)

Use a hover effect like on Apple TV (enlarges the element slightly):

![image](https://github.com/Cryptric/TexCards/assets/87971518/71e31376-b48a-4109-ab58-7c3238edec27)

**Comment by Cryptric** [comment]
Regarding point 5, the tag search is implemented as a disjunctive search query, just showing available tags makes only sense for conjunctive search queries.
Should the search behaviour be changed to find only sets for which all tags match?

**Comment by Cryptric** [comment]
Regarding point 6, click on tag, to search for this tag, should this behaviour exist everywhere or just on the search page?
Same question for the username

**Comment by Cryptric** [comment]
> Regarding point 5, the tag search is implemented as a disjunctive search query, just showing available tags makes only sense for conjunctive search queries. Should the search behaviour be changed to find only sets for which all tags match?

conjunctive search query would make much more sens, but needs issue for backend

**Comment by Cryptric** [comment]
Points 9, and other 9 need backend support, can be rediscussed when the backend has needed functionalities

**Comment by Cryptric** [comment]
Regarding point 11, i would also throw in some shadows and suggest implementing this behaviour everywhere where there are set-summaries.

you can try by adding this snippet to styles.scss
```scss
.card:hover {
  scale: 1.01;
  box-shadow: 0 0 10px gray;
}
```

**Comment by Cryptric** [comment]
Created issues for the backend repository regarding points 5 (change tag search behaviour), 9 and 9.

**Comment by Cryptric** [comment]
Point 5 is not possible at the moment, as the frontend only has some pages, it can't know which tags are available for the applied search terms.
I would disregard this point for now, maybe implement it in a future issue.
However, the backend could send a list of tags available for the applied search terms together with the first page.

**Comment by Cryptric** [comment]
I think implementing a sort function is not worthwhile at the moment, as there are not many sets and last modified, date created are not stored in the database.
But a default sorting on the name could be implemented

**Comment by SamKry** [comment]
> Regarding point 6, click on tag, to search for this tag, should this behaviour exist everywhere or just on the search page?
> Same question for the username

Username could make sense everywhere (highlight as a link?) but tags probably only in the set overview

**Comment by Cryptric** [comment]
> Regarding point 6, click on tag, to search for this tag, should this behaviour exist everywhere or just on the search page? Same question for the username

Everywhere, to a search page with just the corresponding tag selected

**Comment by Cryptric** [comment]
> Regarding point 11, i would also throw in some shadows and suggest implementing this behaviour everywhere where there are set-summaries.
> 
> you can try by adding this snippet to styles.scss
> 
> ```css-scss
> .card:hover {
>   scale: 1.01;
>   box-shadow: 0 0 10px gray;
> }
> ```

make shadow 5px
