### ISSUE TITLE
GUI-General- Confirmation Prompts

### ISSUE THREAD

**Issue by SamKry** [Cryptric/TexCards#48]
# 1. Confirmation Prompts

## Current state

You can perform many actions without having to confirm the intention. This can lead to unintentional actions that can't be undone. 

## Proposal (for discussion)

This is a collection of such actions:
- [ ] (Logout)
- [x] Delete Flashcard Set
- [ ] Delete Card in editing mode
- [x] Leaving `Learn scheduling settings` without saving
- [x] Leaving Edit view without saving

**Comment by Cryptric** [comment]
I think logout does not need a confirmation prompt, as well as deleting a card in editing mode, as the action can be aborted by just not saving the changes._

**Comment by SamKry** [comment]
I agree

**Comment by SamKry** [comment]
Update:

- [ ] Delete Flashcard Set
- [ ] Leaving Learn scheduling settings without saving
- [ ] Leaving Edit view without saving
