### ISSUE TITLE
GUI-set-summary

### ISSUE THREAD

**Issue by SamKry** [Cryptric/TexCards#49]
TODO:
- [x] Capsule Tag Style
- [x] Hide tags if there are many
- [x] Fix the size of a set overview

# 1. Issue Name

Add corner radius to tag to get a capsule shape (like labels here on github).

# 2. Hide tags if there are many

A proposal in GUI enhancement:

## Current state

If there are a lot of tags in a set the set card gets larger. This results in an inconsistent overview.
<img width="700" alt="Bildschirmfoto 2023-09-15 um 15 23 22" src="https://github.com/Cryptric/TexCards/assets/87971518/d566d499-49d4-4312-bd09-79cd843a1069">

## Proposal (for discussion)

<img width="700" alt="Bildschirmfoto 2023-09-15 um 15 23 22" src="https://github.com/Cryptric/TexCards/assets/87971518/064afc9c-8021-4455-b41b-1b4753446216">

# 3. Fix the size of a set overview

A proposal in GUI enhancement:

## Current state

See screenshot above: if there are many tags and or a long description, the set overview grows vertically.

## Proposal (for discussion)

Fix the size and cli the text if needed.

**Comment by Cryptric** [comment]
Rounded corners can be configured by setting the scss variable in `bootstrap-theme.scss`
```scss
// Badge
$badge-border-radius: 10px;
```

**Comment by Cryptric** [comment]
How big should the radius be?
(10px, 3px)
![localhost_4200_profile (3)](https://github.com/Cryptric/TexCards/assets/99428738/a4a8c867-9ef6-4c3f-a93d-1fbe55ca2590)
![localhost_4200_profile (4)](https://github.com/Cryptric/TexCards/assets/99428738/9aa1f21a-01e2-4477-9616-e7d3354f323d)

**Comment by SamKry** [comment]
I think the capsule design looks nice, it separates the tag well from buttons etc.
