### ISSUE TITLE
GUI-Appearance

### ISSUE THREAD

**Issue by SamKry** [Cryptric/TexCards#55]
TODO:
- [x] Automatic detection of System Appearance 
- [x] Toggle/Tab Switch to select Appearance

# 1. Automatic detection of System Appearance 

Automatically detect the current system appearance and set the theme accordingly. 

# 2. Toggle/Tab Switch to select Appearance

A proposal in GUI enhancement:

## Current state
<img width="455" alt="Bildschirmfoto 2023-09-13 um 15 53 21" src="https://github.com/Cryptric/TexCards/assets/87971518/601ca897-7df5-4bbc-bbc5-841b2fb152cf">

Current state is a Button to toggle the Appearance.

## Proposal (for discussion)

![image](https://github.com/Cryptric/TexCards/assets/87971518/e3f36baa-d163-4119-9309-017266dd45d1)

Add a Toggle/Tab Button to select the appearance.

**Comment by Cryptric** [comment]
Move toggle buttons underneath **Appearance**
