### ISSUE TITLE
GUI-Search Tag-Filter

### ISSUE THREAD

**Issue by Cryptric** [Cryptric/TexCards#60]
TODO:
- [ ] Tags after Search

# 1. Tags after Search
A proposal in GUI enhancement:

## Current state
![image](https://github.com/Cryptric/TexCards/assets/99428738/e3e9e18e-5be7-40f4-a67a-574d7081842d)

All tags are present in popup after searching.

## Proposal (for discussion)
Only show available tags after the search term was applied.

**Comment by SamKry** [comment]
not now
